### ISSUE TITLE
Bisync error in 1.4.1. - Critical error: "chtimes /home operation not permitted" when resync

### ISSUE THREAD

**Issue by sleepingpill87** [GedasFX/decky-cloud-save#96] opened 2024-08-30 07:48 UTC
Like in the title. When bisync and then resync these are the logs.

![20240830_092948](https://github.com/user-attachments/assets/562fcefe-a383-48b7-b076-531132ec1964)

![20240830_093016](https://github.com/user-attachments/assets/b96e598d-a797-443a-87f4-4db54b206ac4)

![20240830_093056](https://github.com/user-attachments/assets/61b68736-bed5-48af-aed0-49deb344e703)

**Comment by sleepingpill87** [comment] 2024-08-30 08:23
I add this thread, the problem seems similar.

https://github.com/rclone/rclone/issues/738

**Comment by AkazaRenn** [comment] 2024-08-31 01:33
Related https://github.com/GedasFX/decky-cloud-save/issues/75#issuecomment-2307588861

**Comment by GedasFX** [comment] 2024-08-31 10:37
Yeah this is duplicate of #75 Closing, use that thread.

**Closed by GedasFX** 2024-08-31 10:37 UTC
