### ISSUE TITLE
Add sync path error

### ISSUE THREAD

**Issue by partytoni** [GedasFX/decky-cloud-save#7] opened 2023-03-24 04:01 UTC
Hello, 

I'm stuck on steam loading icon after pressing on "add new path to sync". 

I'm on version 1.1.1 and decky in stable version 2.6.4.

I have already configured dropbox as cloud provider.

**Comment by partytoni** [comment] 2023-03-24 04:18
Fixed after a couple of reboots.

**Comment by GedasFX** [comment] 2023-03-24 07:33
Hey, yeah it seems like people are getting this issue right after installation. I personally was not able to get this bug to show up, and from what I can tell its only from the first installation. Reinstalling this does not make the bug appear...

It seems like a restart is all you need here. If someone finds the actual cause, I can find a fix.

**Comment by GedasFX** [comment] 2023-03-28 07:09
TODO: Add a label in sync paths page where it would say 'you may need to restart steam deck for the file selector to work properly'. Doesn't seem like its caused by the plugin sadly :/

**Comment by Fisch03** [comment] 2023-03-30 17:22
I believe it's enough to just restart Steam instead of the entire Deck. That's at least a bit faster...

**Comment by GedasFX** [comment] 2023-04-02 07:47
I for the life of me could not figure out how to reproduce, so I will just put a help section on what to do in case of that. For now, this issue can stay open until actual fix is in place.

**Comment by GedasFX** [comment] 2023-08-22 20:20
We haven't had this issue for a while, so I think its safe to close.

**Closed by GedasFX** 2023-08-22 20:20 UTC
