### ISSUE TITLE
Can't see a "Use this folder" button when trying to select a file/folder to sync

### ISSUE THREAD

**Issue by pickettd** [GedasFX/decky-cloud-save#23] opened 2023-06-21 04:36 UTC
I have a fresh install and I've tried both the latest version in the plugin store and version 1.3. On my Steam deck I can browse the file system but there is no "Use this folder" button and so I can't add a path to be synced (I understand from watching Youtube videos of the plugin that there should be a button at the bottom to select a file/folder and then a confirmation popup). Is there a manual workaround to consider the folder I want to backup in Desktop Mode? I've also tried rebooting the Steam deck a few times and also just restarting Steam.

Also I noticed that when I choose the option to select a single File - the browser does not show me individual files - just folders

**Comment by GedasFX** [comment] 2023-06-21 07:11
Hey, the latest version was released and I am seeing lots of people having issues with it. I tested it with manual deployment, but not from store. For now try the 1.2.1-1 version, might work.

**Comment by jaakon** [comment] 2023-06-21 08:54
I have a similar issue (v1.3): I can see the button, but clicking on it just closes the dialog. It does not add the selected folder/file.

Maybe this is somehow related. If not, please ignore my comment, I do not want to disturb the original report.

**Comment by GedasFX** [comment] 2023-06-21 08:58
Must be related, I am getting many reports of this not working in 1.3.0.

**Comment by GedasFX** [comment] 2023-06-21 08:59
If you guys could verify if the issue persists in 1.2.1-1 would be great. I will check once I finish work today.

**Comment by satanasinc** [comment] 2023-06-22 06:00
> If you guys could verify if the issue persists in 1.2.1-1 would be great. I will check once I finish work today.

The problem persist. Thanks for this great plugin, nice work!

**Comment by GedasFX** [comment] 2023-06-22 07:31
Guys, I genuinely cannot reproduce this issue. Like i checked everything and it works! Could you provide some screenshots? I genuinely cannot find what would be the issue even 😄

**Comment by GedasFX** [comment] 2023-06-22 07:35
Okay seems like you just need to complain. Turns out issue was caused by the file picker being updated. Works on older versions of decky.

**Comment by GedasFX** [comment] 2023-06-22 07:36
@pickettd As for workaround, yes there are sync configuration files in config folder. Edit includes file there (and restart steam deck just in case). Folders end  with /**

**Comment by satanasinc** [comment] 2023-06-22 07:52
In roder to workaaound the issue i typed my new game save path in this 2 files  /home/deck/homebrew/settings/decky-cloud-save/sync_paths.txt and  /home/deck/homebrew/settings/decky-cloud-save/sync_paths_filter.txt NOTE: folow the complete game path with "**"

**Comment by GedasFX** [comment] 2023-06-22 07:52
Bug relates to https://github.com/SteamDeckHomebrew/decky-loader/pull/454/files

**Comment by satanasinc** [comment] 2023-06-22 07:59
Hi again!
The sceenshot
https://steamuserimages-a.akamaihd.net/ugc/2039615770512180686/DDAE1AA10D35B43F3D974BF7B0E81FA199B1AF0D/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by GedasFX** [comment] 2023-06-22 11:44
Issue confirmed and will be fixed in the next Decky Loader update. You will also need to update the plugin to >1.3.0

**Comment by pickettd** [comment] 2023-06-23 06:51
I did get the workaround to work by editing the files on the Steamdeck with Kate. As @satanasinc mentioned, I put the path that I wanted to backup in the /home/deck/homebrew/settings/decky-cloud-save/sync_paths.txt file by itself (with /** at the end) and then I put a line in the /home/deck/homebrew/settings/decky-cloud-save/sync_paths_filter.txt file that matches with the examples from https://rclone.org/filtering/#examples

Meaning that the sync_paths_filter.txt looked something like this:
```
+ /my-folder-to-backup/**
- **
```

**Comment by GedasFX** [comment] 2023-06-26 18:09
Fixed in PR https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/388.
Until it gets merged, you can use v1.3.1 found in releases.

**Closed by GedasFX** 2023-06-26 18:09 UTC
