### ISSUE TITLE
Can't select file/folder to sync

### ISSUE THREAD

**Issue by Grawler** [GedasFX/decky-cloud-save#27] opened 2023-06-30 12:00 UTC
When I go to the menu to add a sync file/folder, it allows me to browse through folders. However, it doesn't see any files and I can't select a folder. There simple is just no option to do so, it'll either let me go back up and deeper into the folder structure.

I've restarted a couple of times to no avail. It's a fresh install.

https://steamuserimages-a.akamaihd.net/ugc/2029483306234951926/9816963F018A78C9B34537CDCDE7E7CBB91BFBE2/

**Comment by GedasFX** [comment] 2023-06-30 13:04
Hey, duplicate of https://github.com/GedasFX/decky-cloud-save/issues/23. You need to use the prerelease version of decky loader in addition to v1.3.1. Sorry for the inconvenience caused, but the latest version of Loader broke it. Hopefully, the update gets pushed soon.

**Comment by Grawler** [comment] 2023-06-30 17:31
I couldn't get 1.3.1 to install either. In the end I fixed it by editing the config files in desktop mode.

**Closed** 2023-07-10 14:59 UTC
